export type ArtStyle = 'watercolor' | 'cyberpunk' | 'gothic' | 'comic' | 'pixel';

export interface CharacterInfo {
  name: string;
  class: string;
  description: string; // Dynamic description generated by AI at start to maintain consistency
}

export interface PlayerStats {
  health: number;
  maxHealth: number;
  gold: number;
  experience: number;
}

export interface AdventureState {
  premise: string;
  artStyle: ArtStyle;
  character: CharacterInfo;
  stats: PlayerStats;
  inventory: string[];
  currentQuest: string;
  storyHistory: {
    storyText: string;
    choiceMade: string;
    imageUrl?: string;
  }[];
  currentStoryText: string;
  currentChoices: string[];
  currentImageUrl: string | null;
  imageSize: '1K' | '2K' | '4K';
}

export interface AdventureStepResponse {
  storyText: string;
  choices: string[];
  inventoryAdded: string[];
  inventoryRemoved: string[];
  questText: string;
  questStatus: 'started' | 'updated' | 'completed' | 'none';
  imagePrompt: string; // The specific image prompt representing this scene
  healthChange: number; // e.g. -15 or +10
  goldChange: number; // e.g. +20 or -5
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'companion';
  text: string;
  timestamp: string;
}
